"""foundation: shops, users, log tables

Revision ID: 0243c7acf544
Revises: 
Create Date: 2026-07-06 23:53:17.778207

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0243c7acf544'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('SUPERADMIN', 'OWNER', 'RECEIVER_USER', 'CASHIER_USER', name='user_role', native_enum=False, length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='restrict'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'phone', name='uq_users_shop_phone'),
    sa.UniqueConstraint('shop_id', 'username', name='uq_users_shop_username')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_shop_id'), 'users', ['shop_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('admin_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='set null'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_logs_actor_user_id'), 'admin_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_admin_logs_event_type'), 'admin_logs', ['event_type'], unique=False)
    op.create_index('ix_admin_logs_shop_created', 'admin_logs', ['shop_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_admin_logs_shop_id'), 'admin_logs', ['shop_id'], unique=False)
    op.create_table('invoicing_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='set null'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoicing_logs_actor_user_id'), 'invoicing_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_invoicing_logs_event_type'), 'invoicing_logs', ['event_type'], unique=False)
    op.create_index('ix_invoicing_logs_shop_created', 'invoicing_logs', ['shop_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_invoicing_logs_shop_id'), 'invoicing_logs', ['shop_id'], unique=False)
    op.create_table('stockin_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='set null'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stockin_logs_actor_user_id'), 'stockin_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_stockin_logs_event_type'), 'stockin_logs', ['event_type'], unique=False)
    op.create_index('ix_stockin_logs_shop_created', 'stockin_logs', ['shop_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_stockin_logs_shop_id'), 'stockin_logs', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stockin_logs_shop_id'), table_name='stockin_logs')
    op.drop_index('ix_stockin_logs_shop_created', table_name='stockin_logs')
    op.drop_index(op.f('ix_stockin_logs_event_type'), table_name='stockin_logs')
    op.drop_index(op.f('ix_stockin_logs_actor_user_id'), table_name='stockin_logs')
    op.drop_table('stockin_logs')
    op.drop_index(op.f('ix_invoicing_logs_shop_id'), table_name='invoicing_logs')
    op.drop_index('ix_invoicing_logs_shop_created', table_name='invoicing_logs')
    op.drop_index(op.f('ix_invoicing_logs_event_type'), table_name='invoicing_logs')
    op.drop_index(op.f('ix_invoicing_logs_actor_user_id'), table_name='invoicing_logs')
    op.drop_table('invoicing_logs')
    op.drop_index(op.f('ix_admin_logs_shop_id'), table_name='admin_logs')
    op.drop_index('ix_admin_logs_shop_created', table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_event_type'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_actor_user_id'), table_name='admin_logs')
    op.drop_table('admin_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_shop_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_table('shops')
    # ### end Alembic commands ###
