"""eod: eod_signed_off_at + eod_signoffs table

Revision ID: 058759837183
Revises: 2e68e776867b
Create Date: 2026-07-07 01:40:51.243059

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058759837183'
down_revision: str | Sequence[str] | None = '2e68e776867b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eod_signoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signed_off_by_user_id', sa.Integer(), nullable=False),
    sa.Column('signed_off_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('invoices_signed_off', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='restrict'),
    sa.ForeignKeyConstraint(['signed_off_by_user_id'], ['users.id'], ondelete='restrict'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'business_date', name='uq_eod_signoffs_shop_date')
    )
    op.add_column('invoices', sa.Column('eod_signed_off_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('eod_signed_off_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'users', ['eod_signed_off_by_user_id'], ['id'], ondelete='set null')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'eod_signed_off_by_user_id')
    op.drop_column('invoices', 'eod_signed_off_at')
    op.drop_table('eod_signoffs')
    # ### end Alembic commands ###
