"""voids: void/reversal/pending_void status + reverses_invoice_id + void_requested

Revision ID: 2e68e776867b
Revises: ea0fba754aaa
Create Date: 2026-07-07 01:33:16.678125

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e68e776867b'
down_revision: str | Sequence[str] | None = 'ea0fba754aaa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('reverses_invoice_id', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('void_requested_by_user_id', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('void_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_invoices_reverses_invoice_id'), 'invoices', ['reverses_invoice_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'invoices', ['reverses_invoice_id'], ['id'], ondelete='set null')
    op.create_foreign_key(None, 'invoices', 'users', ['void_requested_by_user_id'], ['id'], ondelete='set null')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_reverses_invoice_id'), table_name='invoices')
    op.drop_column('invoices', 'void_requested_at')
    op.drop_column('invoices', 'void_requested_by_user_id')
    op.drop_column('invoices', 'reverses_invoice_id')
    # ### end Alembic commands ###
