"""lots: lot + lot_lines tables

Revision ID: 3efd6817d954
Revises: 423948112aae
Create Date: 2026-07-07 01:12:35.260601

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3efd6817d954'
down_revision: str | Sequence[str] | None = '423948112aae'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('received_by_user_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['users.id'], ondelete='restrict'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lots_received_by_user_id'), 'lots', ['received_by_user_id'], unique=False)
    op.create_index(op.f('ix_lots_shop_id'), 'lots', ['shop_id'], unique=False)
    op.create_index('ix_lots_shop_received_at', 'lots', ['shop_id', 'received_at'], unique=False)
    op.create_table('lot_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lot_lines_product', 'lot_lines', ['product_id'], unique=False)
    op.create_index('uq_lot_lines_lot_product', 'lot_lines', ['lot_id', 'product_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_lot_lines_lot_product', table_name='lot_lines')
    op.drop_index('ix_lot_lines_product', table_name='lot_lines')
    op.drop_table('lot_lines')
    op.drop_index('ix_lots_shop_received_at', table_name='lots')
    op.drop_index(op.f('ix_lots_shop_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_received_by_user_id'), table_name='lots')
    op.drop_table('lots')
    # ### end Alembic commands ###
