"""products: catalog + shop.low_stock_threshold_default

Revision ID: 423948112aae
Revises: 0243c7acf544
Create Date: 2026-07-07 01:01:47.048997

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423948112aae'
down_revision: str | Sequence[str] | None = '0243c7acf544'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=False),
    sa.Column('size_label', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='restrict'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_index('ix_products_shop_barcode', 'products', ['shop_id', 'barcode'], unique=False)
    op.create_index('ix_products_shop_brand', 'products', ['shop_id', 'brand'], unique=False)
    op.create_index(op.f('ix_products_shop_id'), 'products', ['shop_id'], unique=False)
    op.add_column('shops', sa.Column('low_stock_threshold_default', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'low_stock_threshold_default')
    op.drop_index(op.f('ix_products_shop_id'), table_name='products')
    op.drop_index('ix_products_shop_brand', table_name='products')
    op.drop_index('ix_products_shop_barcode', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
