"""invoices: invoice, lines, payments, idempotency + shop.last_invoice_number

Revision ID: ea0fba754aaa
Revises: 3efd6817d954
Create Date: 2026-07-07 01:23:50.620208

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea0fba754aaa'
down_revision: str | Sequence[str] | None = '3efd6817d954'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('cashier_user_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'FINALIZED', 'VOIDED', name='invoice_status', native_enum=False, length=32), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('eod_signed_off', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['cashier_user_id'], ['users.id'], ondelete='restrict'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='restrict'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'invoice_number', name='uq_invoices_shop_number')
    )
    op.create_index('ix_invoices_shop_finalized_at', 'invoices', ['shop_id', 'finalized_at'], unique=False)
    op.create_index('ix_invoices_shop_status', 'invoices', ['shop_id', 'status'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='restrict'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'key', name='uq_idempotency_keys_shop_key')
    )
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='restrict'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'product_id', name='uq_invoice_lines_invoice_product')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('CASH', 'UPI', 'CARD', name='payment_mode', native_enum=False, length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_invoice', 'payments', ['invoice_id'], unique=False)
    op.add_column('shops', sa.Column('last_invoice_number', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'last_invoice_number')
    op.drop_index('ix_payments_invoice', table_name='payments')
    op.drop_table('payments')
    op.drop_table('invoice_lines')
    op.drop_table('idempotency_keys')
    op.drop_index('ix_invoices_shop_status', table_name='invoices')
    op.drop_index('ix_invoices_shop_finalized_at', table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
